### ISSUE TITLE
GenerateNextCreditCardNumber shouldn't generate next number

### ISSUE THREAD

**Issue by kakarotto67** [yurchik11/Kottans#6]
When pass "4999999999999999993", GenerateNextCreditCardNumber  method shouldn't generate next number as no more numbers left for VISA, but your method generates smaller number.

**Comment by yurchik11** [comment]
i corrected the error and refresh code, but I dont understand exactly what you mean,so which result is expected?

**Comment by kakarotto67** [comment]
Issue still exists, but in different form now. Your method generates "5000000000000000005". This number is valid, but this is not VISA number, so in this case your method should return some message like no more valid numbers left for VISA.

**Comment by yurchik11** [comment]
ummmmm, sorry, i didn`t know that method should return message in this case, in the task it has not been said.

**Comment by kakarotto67** [comment]
That is a tricky case, so we left it as a secret to see how people will process it. Anyway, don't worry, I marked your code as Passed.

**Comment by yurchik11** [comment]
okay, i understood it :)
